#!/bin/bash

REPO=http://packages.vmware.com/tools/esx/latest/rhel5/x86_64

RPMS=""
#RPMS="$RPMS vmware-tools-foundation-9.4.10-1.el5.x86_64.rpm"
#RPMS="$RPMS vmware-tools-vmxnet3-common-9.4.10-5.el5.x86_64.rpm"
RPMS="$RPMS kmod-vmware-tools-vmxnet3-1.3.1.0-2.6.18.8.el5.5.el5.x86_64.rpm"

FS=/mnt/tmp-dd2
BLK=vmw.dd.img
KV=2.6.18-8.el5
ARCH=x86_64

mkdir disk
find  disk -exec rm -f {} \;
mkdir -p disk/$KV

for R in $RPMS; do
  mkdir tmp
  curl -qvs "$REPO/$R" -o "tmp/$R"
  (cd tmp && rpm2cpio kmod-vmware-tools-vmxnet3-1.3.1.0-2.6.18.8.el5.5.el5.x86_64.rpm | cpio -iv --make-directories)
  find tmp -name vmxnet3.ko -exec mv {} disk/$KV/$ARCH \;
  rm -rf tmp/
done

echo    "Version 0"                                             > disk/modinfo
echo    "DUD for VMWARE"                                        > disk/rhdd
echo    "15ad  VMware"                                          > disk/pci.ids
echo -e "\t07b0  vmxnet3"                                      >> disk/pci.ids
echo                                                            > disk/modules.dep
echo    "alias: pci:v000015ADd000007B0sv*sd*bc*sc*i* vmxnet3"   > disk/modules.alias
echo    "vmxnet3"                                              >> disk/modinfo
echo -e "\teth"                                                >> disk/modinfo
echo -e "\tVMware vmxnet3 virtual NIC driver"                  >> disk/modinfo

( cd disk 

  find $KV |\
  cpio -o  |\
  gzip -9 -c > modules.cgz

  rm -rf $KV 
)

#( cd disk
#
#  find . | cpio -o | gzip -9 -c > ../vmware.el5.dd
#)

dd of=$BLK if=/dev/zero bs=512k count=1
mkfs -F -t ext2 $BLK     || exit 1
tune2fs -c0 -i0 -r0 $BLK || exit 1
mkdir -p $FS             || exit 1

mount -o loop $BLK $FS   || exit 1

(cd disk && tar cf - .) | (cd $FS && tar xvf -)

umount $FS
